# Group Client route
http://localhost:3002

\* - Авторизованн

## **/signin**
    Страница входа

## **/registaration**
    Страница регистрации

## **/password-reset**
    Страница сброса пароля

## **/password-new**
    Страница для нового пароля

## **/design**
    Страница с дизайном компонентов

## **/:userID**
    Страница профиля

## **/game/:gameID**
    Страница игры
