# Group Client route
http://localhost:3002

\* - Авторизованн

## **/signin**
    Страница входа

## **/registaration**
    Страница регистрации

## **/password-reset**
    Страница сброса пароля

## **/password-new**
    Страница для нового пароля

## **/:userId**
    Страница профиля

## **/:userId/skills**
    Страница профиля - умения

## **/:userId/skills/skillId**
    Страница профиля - умения - умение

## **/:userId/scoreboard**
    Страница профиля - доска почета

## **/:userId/settings**
    Страница профиля - настройки

## **/game/:gameId**
    Страница игры
