# Group Client route
http://localhost:3002

\* - Авторизованн

##  **/** or **/signin**
    Страница входа

## **/registaration**
    Страница регистрации

## **/password-reset**
    Страница сброса пароля

## **/password-new/{hash}**
    Страница для нового пароля

## **/:userId**
    Страница профиля

## **/skills**
    Страница профиля - умения

## **/shop**
    Страница профиля - магазина

## **/chat**
    Страница профиля - тестовый полигон

## **/scoreboard**
    Страница профиля - доска почета

## **/settings**
    Страница профиля - настройки

## **/settings/password**
    Страница профиля - настройки - изменение пароля

## **/settings/account**
    Страница профиля - настройки - привязка соц сетей и удаление аккаунта

## **/settings/nickname**
    Страница профиля - настройки - смена никнейма

## **/game**
    Страница лобби

## **/game/:gameId**
    Страница игры
