# Group Sessions API
\* - Авторизованн

### Вход [POST /signin]
Осуществляет аутентификацию пользователя. Устанавливает TOKEN в localstarage
```
{
  "alg": "HS256",
  "typ": "JWT"
}
{
  "id": "5b6c89e5b6684e51f462a23d",
  "nickname": "Ivan2",
  "iat": 1534304024
}
```
```
HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
  mysecretkey
) 
```
**Result token**
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViNmM4OWU1YjY2ODRlNTFmNDYyYTIzZCIsIm5pY2tuYW1lIjoiSXZhbjIiLCJpYXQiOjE1MzQzMDQ5NjJ9.mkYD3slMipSnftbXvYwtiS1UZsIWFWT55mNOBnxqJhw
```


+ Request (application/json)
    + Attributes
        + email: ivan@mail.ru (string, required)
        + password: password  (string, required)

+ Response 200 (application/json; charset=utf-8)
Вход осуществлен успешно
    + Attributes
        + id: 1 (number)
        + message: You are signed in (string)
        + token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViNmM4OWU1YjY2ODRlNTFmNDYyYTIzZCIsIm5pY2tuYW1lIjoiSXZhbjIiLCJpYXQiOjE1MzQzMDQ5NjJ9.mkYD3slMipSnftbXvYwtiS1UZsIWFWT55mNOBnxqJhw

+ Response 403 (application/json; charset=utf-8)
Переданы неверные параметры входа
    + Attributes
        + message: Incorrect username or password (string)
        + code: forbidden (string)

### * Выход [DELETE /signout]
Осуществляет выход из приложения.

+ Response 200 (application/json; charset=utf-8)
Выход из приложения осуществлен залогиненым пользователем
    + Attributes
        + message: You are signed out (string)
    
+ Response 403 (application/json; charset=utf-8)
Переданы неверные параметры входа
    + Attributes
        + message: Forbidden (string)
        + code: forbidden (string)