# Group Tool API
API для сервисных функций

### Ping [HEAD /ping]
Проверка доступности сервиса

+ Response 200

### Доступность почты [GET /checkEmail{?email}]

Проверка доступности почты
+ Parameters
    + email: Ivan@email.com (string, optional) - почта

+ Response 200 (application/json; charset=utf-8)
Почту **можно** использовать
    + Attributes
        + used: true (boolean) 

+ Response 400 (application/json; charset=utf-8)
Заданы неверные параметры
    + Attributes
        + message: Invalid params
        + code: invalid_params

### Доступность никнейма [GET /checkNickname{?nickname}] 

Проверка доступности никнейма
+ Parameters
    + nickname: Ivan (string, optional) - никнейм

+ Response 200 (application/json; charset=utf-8)
Никнейм **можно** использовать  
    + Attributes
        + used: true (boolean)

+ Response 400 (application/json; charset=utf-8)
Заданы неверные параметры
    + Attributes
        + message: Invalid params
        + code: invalid_params