# Group Users API

### Создание пользователя [POST /users]
Регистрация пользователя

+ Request (application/json; charset=utf-8)
    + Attributes
        + nickname: Ivan (string, required)
        + email: Ivan@email.ru (string, required)
        + password: password123 (string, required)

+ Response 201 (application/json; charset=utf-8)
Пользователь создан успешно
    + Attributes
        + message: Accaunt has been created (string)

+ Response 400 (application/json; charset=utf-8)
Заданы неверные параметры
    + Attributes
        + message: Invalid user params (string)
        + code: invalid_user_params (string)

### Список пользователей [GET /users{?offset,limit}]
Получить список лидеров

+ Parameters
    + offset: 0  (number, optional) - Номер страницы.
    + limit:  10 (number, optional) - Количество элементов на странице.

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + users (array)
            + (object)
                + id: 1 (number)
                + rank: 1 (number)
                + avatar: shooter_1 (string)
                + nickname: Ivan (string)
                + level: 10 (number)
            + (object)
                + id: 2 (number)
                + rank: 2 (number)
                + avatar: shooter_2 (string)
                + nickname: Oleg (string)
                + level: 12 (number)
            + (object)
                + id: 3 (number)
                + rank: 3 (number)
                + avatar: shooter_2 (string)
                + nickname: Makintoshovka (string)
                + level: 11 (number)
            + (object)
                + id: 4 (number)
                + rank: 4 (number)
                + avatar: null (string)
                + nickname: Oleg3 (string)
                + level: 11 (number)
            + (object)
                + id: 5 (number)
                + rank: 5 (number)
                + avatar: shooter_2 (string)
                + nickname: Mava (string)
                + level: 7 (number)
            + (object)
                + id: 6 (number)
                + rank: 10 (number)
                + avatar: shooter_1 (string)
                + nickname: Dmitra (string)
                + level: 5 (number)


    + Schema

            {
                "title": "Users",
                "description": "",
                "type": "object",
                "properties": {
                    "users": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "number"
                                },
                                "nickname": {
                                    "type": "string"
                                },
                                "avatar": {
                                    "type": "string"
                                },
                                "rank": {
                                    "type": "number"
                                },
                            }
                        },
                    }
                }
            }
   
+ Response 404 (application/json; charset=utf-8)
Нет ни одного пользователя
    + Attributes
        + message: Users with id not found (string)
        + code: not_found (string)

### Информация о пользователе [GET /users/{id}]
Получить информацию о пользователе по id

+ Parameters
    + id: 2 (number) - ID пользователя.

+ Response 200 (application/json; charset=utf-8)
Данные пользователя
    + Attributes
        + id: 2 (number) 
        + nickname: Alex (string) 
        + avatar: shooter_3 (string) 
        + rank: 41 (number) 
        + level: 15 (number) 
        + karma: 10 (number) 
        + openSlots: 4 (number) 
        + skillSet (array) 
            + 3 (number, optional) 
            + 1 (number, optional) 
            + 3 (number, optional) 

+ Response 404 (application/json; charset=utf-8)
Пользователь не найден
    + Attributes
        + message: User with id not found (string)
        + code: not_found (string)