

# Group Client route
http://localhost:3002

\* - Авторизованн

## **/**
    Страница входа

## **/***
    Страница профиля

## **/registaration**
    Страница регистрации

## **/password-reset**
    Страница сброса пароля

## **/design**
    Страница с дизайном компонентов