# Group Sessions API
\* - Авторизованн

## Вход [POST /signin]
Осуществляет аутентификацию пользователя. Устанавливает TOKEN в localstarage

+ Request User data

    + Attributes
        + email: ivan@mail.ru (string)
        + password: password  (string)

+ Response 200 (application/json; charset=utf-8)
Вход осуществлен успешно
    + Headers

            Set-Cookie: stringToken

    + Body
    + Attributes
        + message: You are signed in (string)

+ Response 403 (application/json; charset=utf-8)
Переданы неверные параметры входа
    + Attributes
        + message: Forbidden (string)
        + code: forbidden (string)

## * Выход [DELETE /signout]
Осуществляет выход из приложения.

+ Response 200 (application/json; charset=utf-8)
Выход из приложения осуществлен залогиненым пользователем
    + Attributes
        + message: You are signed out (string)
    
+ Response 403 (application/json; charset=utf-8)
Переданы неверные параметры входа
    + Attributes
        + message: Forbidden (string)
        + code: forbidden (string)