# Group Tool API
API для сервисных функций

## Ping [HEAD /ping]
Проверка доступности сервиса

+ Response 200

## Доступность никнейма и почты [GET /check{?nickname,email}]
Проверка доступности никнейма

+ Parameters
    + nickname: Ivan (string, optional) - никнейм
    + email: Ivan@email.com (string, optional) - почта

+ Response 200 (application/json; charset=utf-8)
Никнейм **можно** использовать
    + Attributes
        + nickname: true (boolean)


+ Response 200 (application/json; charset=utf-8)
Никнейм **нельзя** использовать
    + Attributes
        + nickname: false (boolean)

+ Response 200 (application/json; charset=utf-8)
Почту **можно** использовать
    + Attributes
        + email: true (boolean)

+ Response 200 (application/json; charset=utf-8)
Почту **нельзя** использовать
    + Attributes
        + email: false (boolean)

+ Response 400 (application/json; charset=utf-8)
Заданы неверные параметры
    + Attributes
        + message: Invalid params
        + code: invalid_params