# Group Tool API
API для сервисных функций

## Ping [HEAD /ping]
Проверка доступности сервиса

+ Response 200

## Доступность никнейма [GET /check{?nickname}]
Проверка доступности никнейма

+ Parameters
    + nickname: Ivan (string) - никнейм

+ Response 200 (application/json; charset=utf-8)
Никнейм можно использовать
    + Attributes
        + used: false (boolean)


+ Response 200 (application/json)
Никнейм нельзя использовать
    + Attributes
        + used: true (boolean)

+ Response 400 (application/json; charset=utf-8)
Заданы неверные параметры
    + Attributes
        + message: Invalid params
        + code: invalid_params

## Доступность почты [GET /check{?email}]
Проверка доступности почты

+ Parameters
    + email: Ivan@email.com (string) - почта

+ Response 200 (application/json; charset=utf-8)
Почту можно использовать
    + Attributes
        + used: true (boolean)

+ Response 200 (application/json)
Почту нельзя использовать
    + Attributes
        + used: true (boolean)

+ Response 400 (application/json; charset=utf-8)
Заданы неверные параметры
    + Attributes
        + message: Invalid params
        + code: invalid_params